version: '3'

services:
    ambari:
        image: dstreev/ambari-server:${AMBARI_VERSION}
        environment:
          AMBARI_INSTANCE: ${AMBARI_INSTANCE}
        ports:
            - "8080"
            - "22"
#        volumes:
#            - "${ROOT_HDP_DATA_MOUNT}/${DATA_GROUP}/data/node1:/data"
#            - "${ROOT_HDP_DATA_MOUNT}/${DATA_GROUP}/log/node1/hadoop:/var/log/hadoop"
#            - "${ROOT_HDP_DATA_MOUNT}/${DATA_GROUP}/log/node1/hadoop-yarn:/var/log/hadoop-yarn"
#            - "${ROOT_HDP_DATA_MOUNT}/${DATA_GROUP}/log/node1/hadoop-mapreduce:/var/log/hadoop-mapreduce"
#            - "${ROOT_HDP_DATA_MOUNT}/${DATA_GROUP}/log/node1/hive:/var/log/hive"
#            - "${ROOT_HDP_DATA_MOUNT}/${DATA_GROUP}/log/node1/hbase:/var/log/hbase"
#            - "${ROOT_HDP_DATA_MOUNT}/${DATA_GROUP}/log/node1/oozie:/var/log/oozie"
#            - "${ROOT_HDP_DATA_MOUNT}/${DATA_GROUP}/log/node1/falcon:/var/log/falcon"
#            - "${ROOT_HDP_DATA_MOUNT}/${DATA_GROUP}/log/node1/atlas:/var/log/atlas"
#            - "${ROOT_HDP_DATA_MOUNT}/${DATA_GROUP}/log/node1/zookeeper:/var/log/zookeeper"
#            - "${ROOT_HDP_DATA_MOUNT}/${DATA_GROUP}/log/node1/ambari-infra-solr:/var/log/ambari-infra-solr"
#            - "${ROOT_HDP_DATA_MOUNT}/${DATA_GROUP}/log/node1/kafka:/var/log/kafka"
        networks:
            core:
                aliases:
                    - ambari_${AMBARI_INSTANCE}.hdp.local
      #mem_limit: 4G
        deploy:
          mode: replicated
          replicas: 1
#          resources:
#            limits:
#              cpus: '0.5'
#              memory: 2G
#            reservations:
#              cpus: '0.5'
#              memory: 1G
    worker:
        image: dstreev/ambari-agent:${AMBARI_VERSION}
        # This dependency is not for the Ambari Server application, but for the
        # availability to resolve the hostname for ambari-agent start
        environment:
          AMBARI_INSTANCE: ${AMBARI_INSTANCE}
        depends_on:
            - ambari
        ports:
            - "22"
#        volumes:
#            - "${ROOT_HDP_DATA_MOUNT}/${DATA_GROUP}/data/node2:/data"
#            - "${ROOT_HDP_DATA_MOUNT}/${DATA_GROUP}/log/node2/hadoop:/var/log/hadoop"
#            - "${ROOT_HDP_DATA_MOUNT}/${DATA_GROUP}/log/node2/hadoop-yarn:/var/log/hadoop-yarn"
#            - "${ROOT_HDP_DATA_MOUNT}/${DATA_GROUP}/log/node2/hadoop-mapreduce:/var/log/hadoop-mapreduce"
#            - "${ROOT_HDP_DATA_MOUNT}/${DATA_GROUP}/log/node2/hive:/var/log/hive"
#            - "${ROOT_HDP_DATA_MOUNT}/${DATA_GROUP}/log/node2/hbase:/var/log/hbase"
#            - "${ROOT_HDP_DATA_MOUNT}/${DATA_GROUP}/log/node2/falcon:/var/log/falcon"
#            - "${ROOT_HDP_DATA_MOUNT}/${DATA_GROUP}/log/node2/atlas:/var/log/atlas"
#            - "${ROOT_HDP_DATA_MOUNT}/${DATA_GROUP}/log/node2/zookeeper:/var/log/zookeeper"
#            - "${ROOT_HDP_DATA_MOUNT}/${DATA_GROUP}/log/node2/ambari-infra-solr:/var/log/ambari-infra-solr"
#            - "${ROOT_HDP_DATA_MOUNT}/${DATA_GROUP}/log/node2/kafka:/var/log/kafka"
        networks:
            core:
        deploy:
          mode: replicated
          replicas: 1
#          resources:
#            limits:
#              cpus: '0.5'
#              memory: 6G
#            reservations:
#              cpus: '0.5'
#              memory: 2G
    nifi_1:
        image: dstreev/nifi:${NIFI_VERSION}
        # This dependency is not for the Ambari Server application, but for the
        # availability to resolve the hostname for ambari-agent start
        environment:
          AMBARI_INSTANCE: ${AMBARI_INSTANCE}
        depends_on:
            - ambari
        ports:
            - "22"
            - "8080"
        # volumes:
        #     - "${ROOT_HDP_DATA_MOUNT}/${DATA_GROUP}/data/nifi1:/data"
        #     - "${ROOT_HDP_DATA_MOUNT}/${DATA_GROUP}/log/nifi1:/var/log/nifi"
        networks:
            core:
                aliases:
                    - nifi_${AMBARI_INSTANCE}.hdp.local
        deploy:
          mode: replicated
          replicas: 1
#          resources:
#            limits:
#              cpus: '0.5'
#              memory: 2G
#            reservations:
#              cpus: '0.5'
#              memory: 500M

networks:
    core:
        external: true
