version: '3'

services:
    ambari:
        image: dstreev/${OS_VERSION}_ambari
        environment:
          AMBARI_INSTANCE: "${AMBARI_INSTANCE}"
          CLUSTER_PREFIX: "${CLUSTER_PREFIX}"
          AMBARI_SERVER: "true"
          AMBARI_VERSION: "${AMBARI_VERSION}"
          AGENT: "01"
        ports:
            - "8080"
            - "22"
        links:
            - mysql.infra-hdp:db.hdp.local
            - repo.infra-hdp:repo.hdp.local
        volumes:
            - "/var/local/hdp/dk01/data:/data"
#            - "/var/local/hdp/dk01/01/log/hadoop:/var/log/hadoop"
#            - "/var/local/hdp/dk01/01/log/hadoop-yarn:/var/log/hadoop-yarn"
#            - "/var/local/hdp/dk01/01/log/hadoop-mapreduce:/var/log/hadoop-mapreduce"
#            - "/var/local/hdp/dk01/01/log/hive:/var/log/hive"
#            - "/var/local/hdp/dk01/01/log/hbase:/var/log/hbase"
#            - "/var/local/hdp/dk01/01/log/oozie:/var/log/oozie"
#            - "/var/local/hdp/dk01/01/log/falcon:/var/log/falcon"
#            - "/var/local/hdp/dk01/01/log/atlas:/var/log/atlas"
#            - "/var/local/hdp/dk01/01/log/zookeeper:/var/log/zookeeper"
#            - "/var/local/hdp/dk01/01/log/ambari-infra-solr:/var/log/ambari-infra-solr"
#            - "/var/local/hdp/dk01/01/log/kafka:/var/log/kafka"
        networks:
            core:
                aliases:
                    - ${CLUSTER_PREFIX}${AMBARI_INSTANCE}srv.hdp.local
                    - ${CLUSTER_PREFIX}${AMBARI_INSTANCE}agent01.hdp.local
      #mem_limit: 4G
        deploy:
          mode: replicated
          replicas: 1
          placement:
            constraints:
              - node.labels.zone == 1
#          resources:
#            limits:
#              cpus: '0.5'
#              memory: 2G
#            reservations:
#              cpus: '0.5'
#              memory: 1G
    worker_1:
        image: dstreev/${OS_VERSION}_ambari
        # This dependency is not for the Ambari Server application, but for the
        # availability to resolve the hostname for ambari-agent start
        environment:
          AMBARI_INSTANCE: "${AMBARI_INSTANCE}"
          CLUSTER_PREFIX: "${CLUSTER_PREFIX}"
          AMBARI_AGENT: "true"
          AMBARI_VERSION: "${AMBARI_VERSION}"
          AGENT: "02"
        depends_on:
            - ambari
        ports:
            - "22"
        links:
            - mysql.infra-hdp:db.hdp.local
            - repo.infra-hdp:repo.hdp.local
        volumes:
            - "/var/local/hdp/dk01/data:/data"
#            - "/var/local/hdp/dk01/02/log/hadoop:/var/log/hadoop"
#            - "/var/local/hdp/dk01/02/log/hadoop-yarn:/var/log/hadoop-yarn"
#            - "/var/local/hdp/dk01/02/log/hadoop-mapreduce:/var/log/hadoop-mapreduce"
#            - "/var/local/hdp/dk01/02/log/hive:/var/log/hive"
#            - "/var/local/hdp/dk01/02/log/hbase:/var/log/hbase"
#            - "/var/local/hdp/dk01/02/log/oozie:/var/log/oozie"
#            - "/var/local/hdp/dk01/02/log/falcon:/var/log/falcon"
#            - "/var/local/hdp/dk01/02/log/atlas:/var/log/atlas"
#            - "/var/local/hdp/dk01/02/log/zookeeper:/var/log/zookeeper"
#            - "/var/local/hdp/dk01/02/log/ambari-infra-solr:/var/log/ambari-infra-solr"
#            - "/var/local/hdp/dk01/02/log/kafka:/var/log/kafka"
        networks:
            core:
                aliases:
                    - ${CLUSTER_PREFIX}${AMBARI_INSTANCE}agent02.hdp.local
        deploy:
          mode: replicated
          replicas: 1
          placement:
            constraints:
              - node.labels.zone == 2
#          resources:
#            limits:
#              cpus: '0.5'
#              memory: 6G
#            reservations:
#              cpus: '0.5'
#              memory: 2G
    worker_2:
        image: dstreev/${OS_VERSION}_ambari
        # This dependency is not for the Ambari Server application, but for the
        # availability to resolve the hostname for ambari-agent start
        environment:
          AMBARI_INSTANCE: "${AMBARI_INSTANCE}"
          CLUSTER_PREFIX: "${CLUSTER_PREFIX}"
          AMBARI_AGENT: "true"
          AMBARI_VERSION: "${AMBARI_VERSION}"
          AGENT: "03"
        depends_on:
            - ambari
        ports:
            - "22"
        links:
            - mysql.infra-hdp:db.hdp.local
            - repo.infra-hdp:repo.hdp.local
        volumes:
            - "/var/local/hdp/dk01/data:/data"
#            - "/var/local/hdp/dk01/03/log/hadoop:/var/log/hadoop"
#            - "/var/local/hdp/dk01/03/log/hadoop-yarn:/var/log/hadoop-yarn"
#            - "/var/local/hdp/dk01/03/log/hadoop-mapreduce:/var/log/hadoop-mapreduce"
#            - "/var/local/hdp/dk01/03/log/hive:/var/log/hive"
#            - "/var/local/hdp/dk01/03/log/hbase:/var/log/hbase"
#            - "/var/local/hdp/dk01/03/log/oozie:/var/log/oozie"
#            - "/var/local/hdp/dk01/03/log/falcon:/var/log/falcon"
#            - "/var/local/hdp/dk01/03/log/atlas:/var/log/atlas"
#            - "/var/local/hdp/dk01/03/log/zookeeper:/var/log/zookeeper"
#            - "/var/local/hdp/dk01/03/log/ambari-infra-solr:/var/log/ambari-infra-solr"
#            - "/var/local/hdp/dk01/03/log/kafka:/var/log/kafka"
        networks:
            core:
                aliases:
                    - ${CLUSTER_PREFIX}${AMBARI_INSTANCE}agent03.hdp.local
        deploy:
          mode: replicated
          replicas: 1
          placement:
            constraints:
              - node.labels.zone == 3
#          resources:
#            limits:
#              cpus: '0.5'
#              memory: 6G
#            reservations:
#              cpus: '0.5'
#              memory: 2G
    worker_3:
        image: dstreev/${OS_VERSION}_ambari
        # This dependency is not for the Ambari Server application, but for the
        # availability to resolve the hostname for ambari-agent start
        environment:
          AMBARI_INSTANCE: "${AMBARI_INSTANCE}"
          CLUSTER_PREFIX: "${CLUSTER_PREFIX}"
          AMBARI_AGENT: "true"
          AMBARI_VERSION: "${AMBARI_VERSION}"
          AGENT: "04"
        depends_on:
            - ambari
        ports:
            - "22"
        links:
            - mysql.infra-hdp:db.hdp.local
            - repo.infra-hdp:repo.hdp.local
        volumes:
            - "/var/local/hdp/dk01/data:/data"
#            - "/var/local/hdp/dk01/04/log/hadoop:/var/log/hadoop"
#            - "/var/local/hdp/dk01/04/log/hadoop-yarn:/var/log/hadoop-yarn"
#            - "/var/local/hdp/dk01/04/log/hadoop-mapreduce:/var/log/hadoop-mapreduce"
#            - "/var/local/hdp/dk01/04/log/hive:/var/log/hive"
#            - "/var/local/hdp/dk01/04/log/hbase:/var/log/hbase"
#            - "/var/local/hdp/dk01/04/log/oozie:/var/log/oozie"
#            - "/var/local/hdp/dk01/04/log/falcon:/var/log/falcon"
#            - "/var/local/hdp/dk01/04/log/atlas:/var/log/atlas"
#            - "/var/local/hdp/dk01/04/log/zookeeper:/var/log/zookeeper"
#            - "/var/local/hdp/dk01/04/log/ambari-infra-solr:/var/log/ambari-infra-solr"
#            - "/var/local/hdp/dk01/04/log/kafka:/var/log/kafka"
        networks:
            core:
                aliases:
                    - ${CLUSTER_PREFIX}${AMBARI_INSTANCE}agent04.hdp.local
        deploy:
          mode: replicated
          replicas: 1
          placement:
            constraints:
              - node.labels.zone == 4
#          resources:
#            limits:
#              cpus: '0.5'
#              memory: 6G
#            reservations:
#              cpus: '0.5'
#              memory: 2G
    worker_4:
        image: dstreev/${OS_VERSION}_ambari
        # This dependency is not for the Ambari Server application, but for the
        # availability to resolve the hostname for ambari-agent start
        environment:
          AMBARI_INSTANCE: "${AMBARI_INSTANCE}"
          CLUSTER_PREFIX: "${CLUSTER_PREFIX}"
          AMBARI_AGENT: "true"
          AMBARI_VERSION: "${AMBARI_VERSION}"
          AGENT: "05"
        depends_on:
            - ambari
        ports:
            - "22"
        links:
            - mysql.infra-hdp:db.hdp.local
            - repo.infra-hdp:repo.hdp.local
        volumes:
            - "/var/local/hdp/dk01/data:/data"
#            - "/var/local/hdp/dk01/05/log/hadoop:/var/log/hadoop"
#            - "/var/local/hdp/dk01/05/log/hadoop-yarn:/var/log/hadoop-yarn"
#            - "/var/local/hdp/dk01/05/log/hadoop-mapreduce:/var/log/hadoop-mapreduce"
#            - "/var/local/hdp/dk01/05/log/hive:/var/log/hive"
#            - "/var/local/hdp/dk01/05/log/hbase:/var/log/hbase"
#            - "/var/local/hdp/dk01/05/log/oozie:/var/log/oozie"
#            - "/var/local/hdp/dk01/05/log/falcon:/var/log/falcon"
#            - "/var/local/hdp/dk01/05/log/atlas:/var/log/atlas"
#            - "/var/local/hdp/dk01/05/log/zookeeper:/var/log/zookeeper"
#            - "/var/local/hdp/dk01/05/log/ambari-infra-solr:/var/log/ambari-infra-solr"
#            - "/var/local/hdp/dk01/05/log/kafka:/var/log/kafka"
        networks:
            core:
                aliases:
                    - ${CLUSTER_PREFIX}${AMBARI_INSTANCE}agent05.hdp.local
        deploy:
          mode: replicated
          replicas: 1
          placement:
            constraints:
              - node.labels.zone == 5
#          resources:
#            limits:
#              cpus: '0.5'
#              memory: 6G
#            reservations:
#              cpus: '0.5'
#              memory: 2G
    worker_5:
        image: dstreev/${OS_VERSION}_ambari
        # This dependency is not for the Ambari Server application, but for the
        # availability to resolve the hostname for ambari-agent start
        environment:
          AMBARI_INSTANCE: "${AMBARI_INSTANCE}"
          CLUSTER_PREFIX: "${CLUSTER_PREFIX}"
          AMBARI_AGENT: "true"
          AMBARI_VERSION: "${AMBARI_VERSION}"
          AGENT: "06"
        depends_on:
            - ambari
        ports:
            - "22"
        links:
            - mysql.infra-hdp:db.hdp.local
            - repo.infra-hdp:repo.hdp.local
        volumes:
            - "/var/local/hdp/dk01/data:/data"
#            - "/var/local/hdp/dk01/06/log/hadoop:/var/log/hadoop"
#            - "/var/local/hdp/dk01/06/log/hadoop-yarn:/var/log/hadoop-yarn"
#            - "/var/local/hdp/dk01/06/log/hadoop-mapreduce:/var/log/hadoop-mapreduce"
#            - "/var/local/hdp/dk01/06/log/hive:/var/log/hive"
#            - "/var/local/hdp/dk01/06/log/hbase:/var/log/hbase"
#            - "/var/local/hdp/dk01/06/log/oozie:/var/log/oozie"
#            - "/var/local/hdp/dk01/06/log/falcon:/var/log/falcon"
#            - "/var/local/hdp/dk01/06/log/atlas:/var/log/atlas"
#            - "/var/local/hdp/dk01/06/log/zookeeper:/var/log/zookeeper"
#            - "/var/local/hdp/dk01/06/log/ambari-infra-solr:/var/log/ambari-infra-solr"
#            - "/var/local/hdp/dk01/06/log/kafka:/var/log/kafka"
        networks:
            core:
                aliases:
                    - ${CLUSTER_PREFIX}${AMBARI_INSTANCE}agent06.hdp.local
        deploy:
          mode: replicated
          replicas: 1
          placement:
            constraints:
              - node.labels.zone == 6
#          resources:
#            limits:
#              cpus: '0.5'
#              memory: 6G
#            reservations:
#              cpus: '0.5'
#              memory: 2G
    worker_6:
        image: dstreev/${OS_VERSION}_ambari
        # This dependency is not for the Ambari Server application, but for the
        # availability to resolve the hostname for ambari-agent start
        environment:
          AMBARI_INSTANCE: "${AMBARI_INSTANCE}"
          CLUSTER_PREFIX: "${CLUSTER_PREFIX}"
          AMBARI_AGENT: "true"
          AMBARI_VERSION: "${AMBARI_VERSION}"
          AGENT: "07"
        depends_on:
            - ambari
        ports:
            - "22"
        links:
            - mysql.infra-hdp:db.hdp.local
            - repo.infra-hdp:repo.hdp.local
        volumes:
            - "/var/local/hdp/dk01/data:/data"
#            - "/var/local/hdp/dk01/07/log/hadoop:/var/log/hadoop"
#            - "/var/local/hdp/dk01/07/log/hadoop-yarn:/var/log/hadoop-yarn"
#            - "/var/local/hdp/dk01/07/log/hadoop-mapreduce:/var/log/hadoop-mapreduce"
#            - "/var/local/hdp/dk01/07/log/hive:/var/log/hive"
#            - "/var/local/hdp/dk01/07/log/hbase:/var/log/hbase"
#            - "/var/local/hdp/dk01/07/log/oozie:/var/log/oozie"
#            - "/var/local/hdp/dk01/07/log/falcon:/var/log/falcon"
#            - "/var/local/hdp/dk01/07/log/atlas:/var/log/atlas"
#            - "/var/local/hdp/dk01/07/log/zookeeper:/var/log/zookeeper"
#            - "/var/local/hdp/dk01/07/log/ambari-infra-solr:/var/log/ambari-infra-solr"
#            - "/var/local/hdp/dk01/07/log/kafka:/var/log/kafka"
        networks:
            core:
                aliases:
                    - ${CLUSTER_PREFIX}${AMBARI_INSTANCE}agent07.hdp.local
        deploy:
          mode: replicated
          replicas: 1
          placement:
            constraints:
              - node.labels.zone == 7
#          resources:
#            limits:
#              cpus: '0.5'
#              memory: 6G
#            reservations:
#              cpus: '0.5'
#              memory: 2G

#    nifi_1:
#        image: dstreev/${OS_VERSION}_nifi:${NIFI_VERSION}
        # This dependency is not for the Ambari Server application, but for the
        # availability to resolve the hostname for ambari-agent start
#        environment:
#          AMBARI_INSTANCE: "${AMBARI_INSTANCE}"
#          CLUSTER_PREFIX: "${CLUSTER_PREFIX}"
#          AMBARI_AGENT: "true"
#          AMBARI_VERSION: "${AMBARI_VERSION}"
#          AGENT: "08"
#        depends_on:
#            - ambari
#        ports:
#            - "22"
#            - "8080"
#        links:
#            - mysql.infra-hdp:db.hdp.local
#            - repo.infra-hdp:repo.hdp.local
#        volumes:
#            - "/var/local/hdp/dk01/data:/data"
#            - "/var/local/hdp/dk01/08/log/nifi:/var/log/nifi"
#            - "/var/local/hdp/dk01/08/log/hadoop:/var/log/hadoop"
#            - "/var/local/hdp/dk01/08/log/hadoop-yarn:/var/log/hadoop-yarn"
#            - "/var/local/hdp/dk01/08/log/hadoop-mapreduce:/var/log/hadoop-mapreduce"
#            - "/var/local/hdp/dk01/08/log/hive:/var/log/hive"
#            - "/var/local/hdp/dk01/08/log/hbase:/var/log/hbase"
#            - "/var/local/hdp/dk01/08/log/oozie:/var/log/oozie"
#            - "/var/local/hdp/dk01/08/log/falcon:/var/log/falcon"
#            - "/var/local/hdp/dk01/08/log/atlas:/var/log/atlas"
#            - "/var/local/hdp/dk01/08/log/zookeeper:/var/log/zookeeper"
#            - "/var/local/hdp/dk01/08/log/ambari-infra-solr:/var/log/ambari-infra-solr"
#            - "/var/local/hdp/dk01/08/log/kafka:/var/log/kafka"
#        networks:
#            core:
#                aliases:
#                    - ${CLUSTER_PREFIX}${AMBARI_INSTANCE}nifi01.hdp.local
#                    - ${CLUSTER_PREFIX}${AMBARI_INSTANCE}agent08.hdp.local
#        deploy:
#          mode: replicated
#          replicas: 1

networks:
    core:
        external: true
