version: '3'

services:
    repo:
        image: dstreev/hdp-repo
        placement:
          constraints:
            - constraint == repo
        ports:
            - "80"
        volumes:
            - "/data/www:/www"
        networks:
            core:
                aliases:
                    - repo.hdp.local
        mem_limit: 100M
#        resources:
#            limits:
#                cpus: '0.001'
#                memory: 50M
#            reservations:
#                cpus: '0.0001'
#                memory: 20M
    mysql:
        # https://hub.docker.com/_/mysql/
        image: mysql:5.7
        placement:
          constraints:
            - constraint == mysql
        ports:
            - "3306"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        volumes:
            - "/data/mysql/data:/var/lib/mysql"
        networks:
            core:
                aliases:
                    - db.hdp.local
        mem_limit: 500M
#        resources:
#            limits:
#                cpus: '0.100'
#                memory: 500M

networks:
    core:
        external: true
