version: '3'

services:
    repo:
        image: dstreev/hdp-repo
        ports:
            - "80"
        volumes:
            - "/data/www:/www"
        networks:
            core:
                aliases:
                    - repo.hdp.local
        deploy:
          mode: replicated
          replicas: 1
          placement:
            constraints:
              - node.labels.constraint == repo
#        resources:
#            limits:
#                cpus: '0.001'
#                memory: 50M
#            reservations:
#                cpus: '0.0001'
#                memory: 20M
    mysql:
        # https://hub.docker.com/_/mysql/
        image: mysql:5.7
        ports:
            - "3306"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        volumes:
            - "/data/mysql/data:/var/lib/mysql"
        networks:
            core:
                aliases:
                    - db.hdp.local
        deploy:
          mode: replicated
          replicas: 1
          placement:
            constraints:
              - node.labels.constraint == mysql
#        resources:
#            limits:
#                cpus: '0.100'
#                memory: 500M

networks:
    core:
        external: true
